name: RSI a Telegram

# Permisos para permitir push del estado
permissions:
  contents: write

on:
  workflow_dispatch: # Quitar esta linea si se quiere sacar la ejecucion en manual y descomentar
  # los siguientes shcudule con los diempos de ejecucion
#  schedule:
#    # Todos los días, de 10 a 19 hs Argentina (13 a 22 UTC), cada hora
#    - cron: '0 13-22 * * *'
#    # Cada hora de 11 a 17 hs Argentina (UTC-3), lunes a viernes
#    #- cron: '0 14-20 * * 1-5'
#    # Cada 5 minutos
#    #- cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Python 3.10
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias necesarias
      - name: Instalar dependencias
        run: pip install requests yfinance pandas numpy

      # 4️⃣ Ejecutar el script RSI
      - name: Ejecutar script RSI
        run: python mi_script.py
        
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # 5️⃣ Guardar estado actualizado solo si hubo cambios
      - name: Guardar estado RSI actualizado
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add estado_rsi.json
          if ! git diff --cached --quiet; then
            git commit -m "Actualizar estado RSI"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "No hay cambios en estado_rsi.json, no se hace commit"
          fi
